<a href="https://colab.research.google.com/github/LinaMariaCastro/2025-segundo-semestre-ia-economia/blob/main/clases/1_Intro_y_conceptos_fundamentales/1_jupyter_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Econom√≠a I**

- üë©‚Äçüè´ **Profesora:** [Lina Mar√≠a Castro](https://www.linkedin.com/in/lina-maria-castro)  
- üìß **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- üéì **Universidad:** Universidad Externado de Colombia - Facultad de Econom√≠a

# **Conociendo Jupyter Notebook**

Se utiliza Python 3.13.5

## Importar librer√≠as

In [1]:
import numpy as np
import pandas as pd

## Ajustar formato visualizaci√≥n

In [2]:
# Aumentar n√∫mero de columnas que se pueden ver
# Que muestre 500 columnas m√°ximo
pd.options.display.max_columns = 500
# Que muestre todas las columnas
pd.options.display.max_columns = None

In [3]:
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Cargar base de datos

In [4]:
df = pd.read_csv('Base_municipios.txt', sep="|", decimal=',', encoding ='utf-8', converters={'Cod. Municipio':str})
df.head()

,Cod. Municipio,Departamento,Municipio,Poblaci√≥n municipio,Subregi√≥n PDET,ZOMAC,Valor agregado municipio,% Act. primarias municipio,% Act. secundarias municipio,% Act. terciarias municipio,% pobl. con educaci√≥n media municipio,% pobl. con edu. t√©cnica/tecnolog√≠a municipio,% pobl. con pregrado municipio,% pobl. con posgrado municipio,% pobreza municipio,% informalidad municipio,% mujeres municipio,% j√≥venes municipio,% pobl. con discapacidad municipio,% grupos √©tnicos municipio,% pobl. campesina municipio,% pobl. LGBT municipio
0,05001,Antioquia,Medell√≠n,2572350,NaN,0,"66,432.28",0.18,20.06,79.76,26.54,10.34,11.83,3.47,12.80,71.00,52.91,24.48,6.27,2.59,1.90,1.74
1,05002,Antioquia,Abejorral,21109,NaN,1,314.20,45.43,6.37,48.19,12.80,2.46,1.73,0.85,40.60,87.50,47.79,20.51,16.05,0.36,NaN,NaN
2,05004,Antioquia,Abriaqu√≠,2804,NaN,1,38.48,37.04,6.45,56.51,21.40,4.96,2.69,1.07,34.80,87.60,45.79,22.04,16.72,2.04,NaN,NaN
3,05021,Antioquia,Alejandr√≠a,4874,NaN,1,67.95,18.02,6.89,75.08,14.64,5.57,2.92,0.73,31.90,87.10,50.39,20.11,8.10,0.31,NaN,NaN
4,05030,Antioquia,Amag√°,31851,NaN,0,635.93,6.84,46.20,46.96,22.83,5.97,2.95,0.70,22.90,69.50,50.92,23.26,9.02,0.52,NaN,NaN

## Revisar contenido base de datos

In [5]:
# Ver el nombre de todas las columnas
df.columns

Index(['Cod. Municipio', 'Departamento', 'Municipio', 'Poblaci√≥n municipio',
       'Subregi√≥n PDET', 'ZOMAC', 'Valor agregado municipio',
       '% Act. primarias municipio', '% Act. secundarias municipio',
       '% Act. terciarias municipio', '% pobl. con educaci√≥n media municipio',
       '% pobl. con edu. t√©cnica/tecnolog√≠a municipio',
       '% pobl. con pregrado municipio', '% pobl. con posgrado municipio',
       '% pobreza municipio', '% informalidad municipio',
       '% mujeres municipio', '% j√≥venes municipio',
       '% pobl. con discapacidad municipio', '% grupos √©tnicos municipio',
       '% pobl. campesina municipio', '% pobl. LGBT municipio'],
      dtype='object')

In [6]:
# Ver n√∫mero de filas y columnas
df.shape

(1122, 22)

In [7]:
# Ver la cantidad de filas del df
len(df)

1122

In [8]:
# Ver los tipos de datos de cada columna
df.dtypes

Cod. Municipio                                    object
Departamento                                      object
Municipio                                         object
Poblaci√≥n municipio                                int64
Subregi√≥n PDET                                    object
ZOMAC                                              int64
Valor agregado municipio                         float64
% Act. primarias municipio                       float64
% Act. secundarias municipio                     float64
% Act. terciarias municipio                      float64
% pobl. con educaci√≥n media municipio            float64
% pobl. con edu. t√©cnica/tecnolog√≠a municipio    float64
% pobl. con pregrado municipio                   float64
% pobl. con posgrado municipio                   float64
% pobreza municipio                              float64
% informalidad municipio                         float64
% mujeres municipio                              float64
% j√≥venes municipio                              float64
% pobl. con discapacidad municipio               float64
% grupos √©tnicos municipio                       float64
% pobl. campesina municipio                      float64
% pobl. LGBT municipio                           float64
dtype: object

In [9]:
# Ver la cantidad de filas y columnas, el nombre todas las columnas, el tipo de datos y si tiene nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 22 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Cod. Municipio                                 1122 non-null   object
 1   Departamento                                   1122 non-null   object
 2   Municipio                                      1122 non-null   object
 3   Poblaci√≥n municipio                            1122 non-null   int64
 4   Subregi√≥n PDET                                 170 non-null    object
 5   ZOMAC                                          1122 non-null   int64
 6   Valor agregado municipio                       1121 non-null   float64
 7   % Act. primarias municipio                     1121 non-null   float64
 8   % Act. secundarias municipio                   1121 non-null   float64
 9   % Act. terciarias municipio                    1121 non-null   float64
 10  % pobl. con educaci√≥n media municipio          1122 non-null   float64
 11  % pobl. con edu. t√©cnica/tecnolog√≠a municipio  1122 non-null   float64
 12  % pobl. con pregrado municipio                 1122 non-null   float64
 13  % pobl. con posgrado municipio                 1122 non-null   float64
 14  % pobreza municipio                            1122 non-null   float64
 15  % informalidad municipio                       1122 non-null   float64
 16  % mujeres municipio                            1121 non-null   float64
 17  % j√≥venes municipio                            1121 non-null   float64
 18  % pobl. con discapacidad municipio             1122 non-null   float64
 19  % grupos √©tnicos municipio                     1122 non-null   float64
 20  % pobl. campesina municipio                    24 non-null     float64
 21  % pobl. LGBT municipio                         24 non-null     float64
dtypes: float64(16), int64(2), object(4)
memory usage: 193.0+ KB